version: 2

defaults: &defaults
  working_directory: /sourceforts-infrastructure
  docker:
    - image: hashicorp/terraform

jobs:
  init:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /sourceforts-infrastructure
      - checkout
      - run: terraform init
  validate:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /sourceforts-infrastructure
      - run: terraform validate
  plan:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /sourceforts-infrastructure
      - run: terraform plan
  apply:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /sourceforts-infrastructure
      - run: terraform apply

workflows:
  version: 2
  main:
    jobs:
      - init:
          context: sourceforts-server
      - validate:
          context: sourceforts-server
          requires:
            - init
      - plan:
          context: sourceforts-server
          requires:
            - validate
      - hold-apply:
          type: approval
          requires:
            - plan
      - apply:
          context: sourceforts-server
          requires:
            - hold-apply
