version: 2

defaults: &defaults
  working_directory: /sourceforts-infrastructure
  docker:
    - image: hashicorp/terraform

jobs:
  destroy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /sourceforts-infrastructure
      - run: terraform destroy -force=true
  init:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /sourceforts-infrastructure
      - checkout
      - run: terraform init
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  validate:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /sourceforts-infrastructure
      - run: terraform validate
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  plan:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /sourceforts-infrastructure
      - run: terraform plan -refresh=true
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  apply:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /sourceforts-infrastructure
      - run: terraform apply -auto-approve -refresh=true

workflows:
  version: 2
  main:
    jobs:
      - init:
          context: sourceforts-server
      - destroy:
          context: sourceforts-server
          requires:
            - init
